[package]
name = "day23"
version = "0.1.0"
authors = ["Castell, Massimo <Massimo.Castell@durr.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modulo = "0.1.2"
